name: "process data"
on: push
  #schedule:
  #  - cron: '0 * * * *'
jobs:
  process_data:
    name: Process data
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Resolve dependencies
      run: npm install
    - name: Pull IT latest data
      run: sh it/fetch-data.sh
    - name: Pull UK latest data
      run: sh uk/fetch-data.sh
    - name: Translate data
      run: node it/process-data.js
    - name: Commit translated data
      uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: "Update data sets"
        repository: .
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v1
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Convert IT CSV to sqlite db
      run: csvs-to-sqlite it/data/national-data.csv it/data/it-national.db
    - name: Convert UK cases CSV to sqlite db
      run: csvs-to-sqlite uk/data/uk-national-cases.csv uk/data/uk-national-cases.db
    - name: Convert UK deaths CSV to sqlite db
      run: csvs-to-sqlite uk/data/uk-national-deaths.csv uk/data/uk-national-deaths.db
    - name: Deploy Datasette using Zeit Now
      env:
        NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
      run: |-
        datasette publish now2 \
          it/data/it-national.db \
          uk/data/uk-national-cases.db \
          uk/data/uk-national-deaths.db \
          --token $NOW_TOKEN \
          --project covid-19-datasets \
          --metadata metadata.json